package es.fdi.eventsoft.Negocio.Comandos;

public enum EventosNegocio {
    //******** EVENTOS NEGOCIO USUARIOS ************
    CREAR_USUARIO,
    USUARIO_CREADO,
    ERROR_CREAR_USUARIO,

    BUSCAR_USUARIO,
    ERROR_BUSCAR_USUARIO,

    ELIMINAR_USUARIO,
    ERROR_ELIMINAR_USUARIO,

    MODIFICAR_USUARIO,
    ERROR_MODIFICAR_USUARIO,

    EMAIL_YA_EXISTENTE,


    //******** EVENTOS NEGOCIO VALORACIONES ************


    CREAR_VALORACION,
    ERROR_CREAR_VALORACION,

    BUSCAR_VALORACION,
    ERROR_BUSCAR_VALORACION,

    ELIMINAR_VALORACION,
    ERROR_ELIMINAR_VALORACION,

    BUSCAR_VALORACION_BY_USUARIO,



    //******** EVENTOS NEGOCIO MENSAJES ************


    CREAR_MENSAJE,
    ERROR_CREAR_MENSAJE,

    BUSCAR_MENSAJE,
    ERROR_BUSCAR_MENSAJE,

    ELIMINAR_MENSAJE,
    ERROR_ELIMINAR_MENSAJE,

    BUSCAR_MENSAJES_BY_USER_EMISOR,
    BUSCAR_MENSAJES_BY_USER_RECEPTOR,




    //******** EVENTOS NEGOCIO SERVICIOS ************

    CREAR_SERVICIO,
    ERROR_CREAR_SERVICIO,

    BUSCAR_SERVICIO,
    ERROR_BUSCAR_SERVICIO,

    MODIFICAR_SERVICIO,
    ERROR_MODIFICAR_SERVICIO,

    ELIMINAR_SERVICIO,
    ERROR_ELIMINAR_SERVICIO,

    BUSCAR_SERVICIOS_BY_PROVEEDOR,
    BUSCAR_SERVICIOS_BY_EVENTO,
    BUSCAR_SERVICIOS_ENTRE_FECHAS,



    //******** EVENTOS NEGOCIO EVENTOS ************



    CREAR_EVENTO,
    ERROR_CREAR_EVENTO,

    BUSCAR_EVENTO,
    ERROR_BUSCAR_EVENTO,

    MODIFICAR_EVENTO,
    ERROR_MODIFICAR_EVENTO,

    ELIMINAR_EVENTO,
    ERROR_ELIMINAR_EVENTO,

    BUSCAR_EVENTOS_BY_USUARIO;


}